# -*- coding: utf-8 -*-
"""20230913_4120E012.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AGnN59MfljucuTEhJqsHBRORPO6MknjS
"""

3**211